services:
  localstack:
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,rds
      - RDS_DATA_API=true
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_init.sh:/docker-entrypoint-initaws.d/localstack_init.sh"  
    command: >
      sh -c "chmod +x /docker-entrypoint-initaws.d/localstack_init.sh &&
             /docker-entrypoint-initaws.d/localstack_init.sh"
